export enum UserRoles {
    IndividualExpertLP = "individualexpert-lp",
    IndividualTranslatorLP = "individualtranslator-lp",
    TranslationHouseOwnerLP = "translationhouseowner-lp",
    ExpertHouseOwnerLP = "experthouseowner-lp",
    HouseLegalRepresentativeLP = "houselegalrepresentative-lp",
    ExamReviewerLP = "examreviewer-lp",
    TrainingManagerLP = "trainingmanager-lp",
    ExpertsDepartmentHeadLP = "expertsdepartmenthead-lp",
    SystemAdminCore = "systemadmin-core",
    IndividualClaimantCore = "individualclaimant-core",
    PublicLegalEntityRepresentativeCore = "publiclegalentityrepresentative-core",
    PrivateLegalEntityRepresentativeCore = "privatelegalentityrepresentative-core",
    AuthorizedSignatoryCore = "authorizedsignatory-core",
    CourtJudgeCore = "courtjudge-core",
    CaseManagerCore = "casemanager-core",
    CourtJudgeLF = "courtjudge-lf",
    CaseManagerLF = "casemanager-lf",
    IndividualClaimantLF = "individualclaimant-lf",
    PublicLegalEntityRepresentativeLF = "publiclegalentityrepresentative-lf",
    PrivateLegalEntityRepresentativeLF = "privatelegalentityrepresentative-lf",
    AuthorizedSignatoryLF = "authorizedsignatory-lf"
}